config/routes.rb
NippoCore::Engine.routes.draw do
  devise_for :users, class_name: "NippoCore::User", module: :'nippo_core/users'
  resource :users, path: :user, only: :show
  resources :groups, except: [:destroy] do
    # resources :users, module: :groups, only: [] do
    # end
    resources :group_member_relations, path: :group_members, only: [:new, :create] do
      get :unaccepted, on: :collection
    end
    resources :reports, except: [:destroy]
    post :request_join
  end
  resources :group_member_relations, path: :group_members, only: [] do
    post :accept
  end

  root 'home#index'
end

app/models/nippo_core/application_record.rb
module NippoCore
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/nippo_core/comment.rb
module NippoCore
  class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :report

    validates :user, presence: true
    validates :report, presence: true
    validates :body, presence: true
  end
end

app/models/nippo_core/group.rb
module NippoCore
  class Group < ApplicationRecord
    belongs_to :creator, class_name: 'NippoCore::User'
    has_many :reports, dependent: :destroy
    has_many :users, through: :group_member_relations
    has_many :group_member_relations, dependent: :destroy

    validates :creator, presence: true
    validates :name, presence: true

    def member?(user)
      group_member_relations.where.not(accepted_at: nil).exists?(user_id: user.id)
    end

    # TODO: implement test
    def unaccepted_requests
      group_member_relations.where(accepted_at: nil).includes(:user)
    end

    # TODO: implement test
    def members
      NippoCore::User.joins(:group_member_relations)
                     .where(nippo_core_group_member_relations: {group_id: self.id})
                     .where.not(nippo_core_group_member_relations: {accepted_at: nil})
    end
  end
end

app/models/nippo_core/group_member_relation.rb
module NippoCore
  class GroupMemberRelation < ApplicationRecord
    belongs_to :user
    belongs_to :group
    # TODO: reflect test to optional
    belongs_to :accepter, class_name: 'NippoCore::User', optional: true

    validates :user, presence: true
    validates :group, presence: true
    validates :authentication, presence: true
  end
end

app/models/nippo_core/report.rb
module NippoCore
  class Report < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_many :comments, dependent: :destroy

    validates :user, presence: true
    validates :group, presence: true
    validates :reported_at, presence: true
    validates :body, presence: true
  end
end

app/models/nippo_core/user.rb
module NippoCore
  class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    has_many :created_groups, class_name: 'NippoCore::Group', foreign_key: 'creator_id', dependent: :destroy
    has_many :reports, dependent: :destroy
    has_many :group_member_relations, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :last_name, presence: true
    validates :first_name, presence: true
    validates :nickname, presence: true

    def send_request(group)
      relation = group_member_relations.find_or_initialize_by(group: group)
      relation.save
    end

    # TODO: had better check!
    def add_member(user, group)
      relation = group.group_member_relations.find_or_initialize_by(user: user, accepted_at: nil)
      relation.accepted_at = Time.now
      relation.accepter = self
      relation.save
    end

    def accept_request(request)
      return unless request.group.member?(self)
      request.accepted_at = Time.now
      request.accepter = self
      request.save
    end

    def request_to?(group)
      group_member_relations.exists?(group_id: group.id)
    end

    # TODO: implement test
    def joined_groups
      NippoCore::Group.joins(:group_member_relations)
                      .where(nippo_core_group_member_relations: {user_id: id})
                      .where.not(nippo_core_group_member_relations: {accepted_at: nil})
    end

    # TODO: implement test
    def requesting_groups
      NippoCore::Group.joins(:group_member_relations)
                      .where(nippo_core_group_member_relations: {user_id: id, accepted_at: nil})
    end
  end
end

app/controllers/nippo_core/application_controller.rb
module NippoCore
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!

  private
    def find_group
      @group = NippoCore::Group.find(params[:group_id] || params[:id])
    end
  end
end

app/controllers/nippo_core/group_member_relations_controller.rb
module NippoCore
  class GroupMemberRelationsController < ApplicationController
    before_action :find_group, except: :accept

    def new
      @group_member_relations = @group.group_member_relations.new
    end

    # TODO: Implement test
    def create
      redirect_to home_path and return unless @group.member?(current_user)
      user = NippoCore::User.find(params[:group_member_relation][:user_id])
      current_user.add_member(user, @group)

      redirect_to group_path(@group)
    end

    def accept
      @request = NippoCore::GroupMemberRelation.find(params[:group_member_relation_id])
      current_user.accept_request(@request)

      render layout: nil
    end

    def unaccepted
      @requests = @group.unaccepted_requests.limit(5)
    end
  end
end

app/controllers/nippo_core/groups/users_controller.rb
module NippoCore
  module Groups
    class UsersController < ApplicationController
      before_action :find_group

      def unaccepted
        @requests = @group.unaccepted_requests.limit(5)
      end
    end
  end
end

app/controllers/nippo_core/groups_controller.rb
module NippoCore
  class GroupsController < ApplicationController
    include Pundit

    before_action :initialize_group, only: [:new, :create]
    before_action :find_group, except: [:index, :new, :create]

    def index
      @groups = NippoCore::Group.order(created_at: :desc).page(params[:page]).per(10)
    end

    def new
    end

    def show
      @reports = @group.reports.order(reported_at: :desc).limit(5)
      @requests = @group.unaccepted_requests.limit(5)
      @members = @group.members
    end

    def create
      if @group.save
        current_user.add_member(current_user, @group)
        redirect_to root_path
      else
        render 'new', status: 400
      end
    end

    def edit
      authorize @group
      render layout: nil
    end

    def update
      authorize @group
      if @group.update(group_params)
        redirect_to @group
      else
        head 400
      end
    end

    def request_join
      result = current_user.send_request(@group)
      render layout: nil
    end

  private
    def initialize_group
      @group = NippoCore::Group.new(group_params.merge(creator: current_user))
    end

    def group_params
      params.fetch(:group, {}).permit(:name, :description, :reported_at)
    end
  end
end

app/controllers/nippo_core/home_controller.rb
module NippoCore
  class HomeController < ApplicationController
    skip_before_action :authenticate_user!

    def index
    end
  end
end

app/controllers/nippo_core/reports_controller.rb
module NippoCore
  class ReportsController < ApplicationController
    include Pundit
    before_action :find_group
    before_action :initialize_report, except: :index

    # TODO: Implement test
    def index
      redirect_to home_path unless @group.member?(current_user)
      @reports = @group.reports.order(reported_at: :desc).page(params[:page]).per(10)
    end

    def show
      authorize @report
    end

    def new
      authorize @report
    end

    def create
      authorize @report
      if @report.save
        redirect_to group_reports_path(group_id: @group.id)
      else
        render 'new', status: 400
      end
    end

    def edit
      authorize @report
      render layout: nil
    end

    def update
      authorize @report
      if @report.update(report_params)
        redirect_to [@group, @report]
      else
        head 400
      end
    end

  private
    def initialize_report
      # TODO: integrate parmas[:report][:reported_at]
      @report = @group.reports.find_by(id: params[:id]) || @group.reports.new(report_params.merge(reported_at: params.fetch(:report, {})[:reported_at] || Date.today, user: current_user))
    end

    def report_params
      params.fetch(:report, {}).permit(:body)
    end
  end
end

app/controllers/nippo_core/users/confirmations_controller.rb
class NippoCore::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/nippo_core/users/omniauth_callbacks_controller.rb
class NippoCore::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/nippo_core/users/passwords_controller.rb
class NippoCore::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/nippo_core/users/registrations_controller.rb
class NippoCore::Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  layout 'nippo_core/application'
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :nickname])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/nippo_core/users/sessions_controller.rb
class NippoCore::Users::SessionsController < Devise::SessionsController
  layout 'nippo_core/application'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/nippo_core/users/unlocks_controller.rb
class NippoCore::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/nippo_core/users_controller.rb
module NippoCore
  class UsersController < ApplicationController
    before_action :authenticate_user!

    def show
      @created_groups = current_user.created_groups.order(created_at: :desc).limit(5)
      @joined_groups = current_user.joined_groups.order(created_at: :desc).limit(5)
      @requesting_groups = current_user.requesting_groups.order(created_at: :desc).limit(5)
    end
  end
end

app/helpers/nippo_core/application_helper.rb
module NippoCore
  module ApplicationHelper
  end
end

app/views/nippo_core/groups/_form.slim
= form_for group do |f|
  .form-group
    = f.label :name
    = f.text_field :name, placeholder: 'グループ名 (必須)', class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, placeholder: '説明', class: 'form-control'
  button.btn.btn-default
    = group.persisted? ? 'Update Group' : 'Create Group'

app/views/nippo_core/groups/edit.js.erb
$("#group-content-area").html('<%= j render 'form', group: @group %>');

app/views/nippo_core/groups/index.slim
- breadcrumb :groups
h1
  | Group index
ul.list-group
  - @groups.each do |group|
    li.list-group-item
      div style="display: flex; justify-content: space-between; align-items: center"
        = link_to group.name, group
        - if group.member?(current_user)
          .btn.btn-success
            | Member
        - else
          = render 'link_to_join', group: group
= paginate @groups

app/views/nippo_core/groups/new.slim
- breadcrumb :new_group
= render 'form', group: @group

app/views/nippo_core/groups/request_join.js.erb
let $link = $("#link-to-join-group_<%= @group.id %>");
$link.attr("href", "#").text("Requesting...").attr("class", "btn btn-warning");

app/views/nippo_core/groups/show.slim
- breadcrumb :group, @group
#group-area.panel.panel-default
  .panel-heading
    div style="display: flex; justify-content: space-between; align-items: center"
      h1.panel-title
        | Group name: 
        = @group.name
      - if policy(@group).edit?
        = link_to 'edit', edit_group_path(@group), remote: true, class: 'btn btn-default'
  .panel-body#group-content-area
    section
      h2
        | Introduction
      = simple_format @group.description
      section
        h3
          | Member
        ul.list-group
          - @members.each do |m|
            li.list-group-item
              = m.nickname
    - if @group.member?(current_user)
      section
        h2
          | Weekly Index
        - week_start_day = Date.today.at_beginning_of_week.yesterday
        table.table
          thead
            th.text-center
              | メンバー
            - 7.times do |d|
              th.text-center*{class: week_start_day == Date.today ? 'warning' : nil}
                = week_start_day + d
          tbody
            - # TODO: DRY
            tr.info
              td.text-center
                = current_user.nickname
              - 7.times do |d|
                - report = @group.reports.find_by(user: current_user, reported_at: week_start_day + d)
                td.text-center*{class: week_start_day + d === Date.today ? 'warning' : nil}
                  - if report.present?
                    = link_to '○', [@group, report]
                  - else
                    = link_to '×', new_group_report_path(group_id: @group.id, report: {reported_at: week_start_day + d})
            - @group.members.where.not(id: current_user.id).each do |member|
              tr
                td.text-center
                  = member.nickname
                - 7.times do |d|
                  - report = @group.reports.find_by(user: member, reported_at: week_start_day + d)
                  td.text-center*{class: week_start_day + d == Date.today ? 'warning' : nil}
                    - if report.present?
                      = link_to '○', [@group, report]
                    - else
                      | ×
    section
      - if @group.member?(current_user)
        section
          h2
            | recently activity
          ul.list-group
            - @reports.each do |report|
              li.list-group-item
                = link_to report.title, [@group, report]
          .btn-group
          = link_to 'more', group_reports_path(group_id: @group.id), class: 'btn btn-link'
          = link_to 'new report', new_group_report_path(group_id: @group.id), class: 'btn btn-link'
        section
          h2
            | requests
          ul.list-group
            - @requests.each do |request|
              li.list-group-item id="request_#{request.id}"
                = request.user.nickname
                |  
                = link_to 'accept', group_member_relation_accept_path(group_member_relation_id: request.id), method: :post, remote: true, id: "link-to-accept-request_#{request.id}"
          = link_to 'more', unaccepted_group_group_member_relations_path(group_id: @group.id), class: 'btn btn-link'
          = link_to 'invite_member', new_group_group_member_relation_path(group_id: @group.id), class: 'btn btn-link'
      - else
        h2
          | Join us?
        = render 'link_to_join', group: @group, class: 'btn btn-link'